import { ISingleSalary } from "@/types";

const data: ISingleSalary[] = [
  {
    companyName: "Tata Consultancy Services",
    jobFunction: "Software Engineering",
    experience: 5.2,
    salary: 1523000,
    domainName: "tcs.com",
    stage: "Public India",
  },
  {
    companyName: "Infosys",
    jobFunction: "Operations",
    experience: 8.5,
    salary: 2175000,
    domainName: "infosys.com",
    stage: "Public India",
  },
  {
    companyName: "Google",
    jobFunction: "Product Manager",
    experience: 6.8,
    salary: 3125000,
    domainName: "google.com",
    stage: "Public Global",
  },
  {
    companyName: "Amazon",
    jobFunction: "Marketing",
    experience: 4.3,
    salary: 1765000,
    domainName: "amazon.in",
    stage: "Public Global",
  },
  {
    companyName: "Flipkart",
    jobFunction: "Product Designer",
    experience: 3.2,
    salary: 1235000,
    domainName: "flipkart.com",
    stage: "Unicorn",
  },
  {
    companyName: "Oracle",
    jobFunction: "Sales",
    experience: 7.7,
    salary: 2625000,
    domainName: "oracle.com",
    stage: "Public Global",
  },
  {
    companyName: "Ola",
    jobFunction: "Software Engineering",
    experience: 2.4,
    salary: 865000,
    domainName: "olacabs.com",
    stage: "Unicorn",
  },
  {
    companyName: "Microsoft",
    jobFunction: "Consulting",
    experience: 9.5,
    salary: 3625000,
    domainName: "microsoft.com",
    stage: "Public Global",
  },
  {
    companyName: "Zomato",
    jobFunction: "Operations",
    experience: 5.3,
    salary: 1675000,
    domainName: "zomato.com",
    stage: "Unicorn",
  },
  {
    companyName: "Wipro",
    jobFunction: "Software Engineering",
    experience: 4.1,
    salary: 1135000,
    domainName: "wipro.com",
    stage: "Public India",
  },
  {
    companyName: "Swiggy",
    jobFunction: "Marketing",
    experience: 3.7,
    salary: 1085000,
    domainName: "swiggy.com",
    stage: "Unicorn",
  },
  {
    companyName: "Adobe",
    jobFunction: "Product Designer",
    experience: 6.6,
    salary: 2925000,
    domainName: "adobe.com",
    stage: "Public Global",
  },
  {
    companyName: "Paytm",
    jobFunction: "Sales",
    experience: 4.4,
    salary: 1365000,
    domainName: "paytm.com",
    stage: "Unicorn",
  },
  {
    companyName: "Cognizant",
    jobFunction: "Software Engineering",
    experience: 7.2,
    salary: 1965000,
    domainName: "cognizant.com",
    stage: "Public Global",
  },
  {
    companyName: "MakeMyTrip",
    jobFunction: "Product Manager",
    experience: 5.8,
    salary: 2175000,
    domainName: "makemytrip.com",
    stage: "Unicorn",
  },
  {
    companyName: "Goldman Sachs",
    jobFunction: "Consulting",
    experience: 8.3,
    salary: 3275000,
    domainName: "goldmansachs.com",
    stage: "Public Global",
  },
  {
    companyName: "Myntra",
    jobFunction: "Operations",
    experience: 3.5,
    salary: 935000,
    domainName: "myntra.com",
    stage: "Unicorn",
  },
  {
    companyName: "Accenture",
    jobFunction: "Software Engineering",
    experience: 6.4,
    salary: 1765000,
    domainName: "accenture.com",
    stage: "Public Global",
  },
  {
    companyName: "Snapdeal",
    jobFunction: "Marketing",
    experience: 4.7,
    salary: 1275000,
    domainName: "snapdeal.com",
    stage: "Unicorn",
  },
  {
    companyName: "Dell",
    jobFunction: "Sales",
    experience: 5.6,
    salary: 1865000,
    domainName: "dell.com",
    stage: "Public Global",
  },
  {
    companyName: "Oyo",
    jobFunction: "Software Engineering",
    experience: 2.1,
    salary: 735000,
    domainName: "oyorooms.com",
    stage: "Unicorn",
  },
  {
    companyName: "Cisco",
    jobFunction: "Product Manager",
    experience: 7.4,
    salary: 2975000,
    domainName: "cisco.com",
    stage: "Public Global",
  },
  {
    companyName: "UrbanClap",
    jobFunction: "Operations",
    experience: 3.9,
    salary: 1165000,
    domainName: "urbancompany.com",
    stage: "Unicorn",
  },
  {
    companyName: "Salesforce",
    jobFunction: "Sales",
    experience: 5.2,
    salary: 2275000,
    domainName: "salesforce.com",
    stage: "Public Global",
  },
  {
    companyName: "Freshworks",
    jobFunction: "Software Engineering",
    experience: 4.6,
    salary: 1465000,
    domainName: "freshworks.com",
    stage: "Unicorn",
  },
  {
    companyName: "SAP Labs",
    jobFunction: "Consulting",
    experience: 6.3,
    salary: 2675000,
    domainName: "sap.com",
    stage: "Public Global",
  },
  {
    companyName: "BigBasket",
    jobFunction: "Marketing",
    experience: 3.1,
    salary: 1035000,
    domainName: "bigbasket.com",
    stage: "Unicorn",
  },
  {
    companyName: "VMware",
    jobFunction: "Software Engineering",
    experience: 8.7,
    salary: 3125000,
    domainName: "vmware.com",
    stage: "Public Global",
  },
  {
    companyName: "Nykaa",
    jobFunction: "Product Designer",
    experience: 5.4,
    salary: 1865000,
    domainName: "nykaa.com",
    stage: "Unicorn",
  },
  {
    companyName: "Intel",
    jobFunction: "Software Engineering",
    experience: 7.5,
    salary: 2875000,
    domainName: "intel.com",
    stage: "Public Global",
  },
  {
    companyName: "Lenskart",
    jobFunction: "Operations",
    experience: 4.2,
    salary: 1365000,
    domainName: "lenskart.com",
    stage: "Unicorn",
  },
  {
    companyName: "Uber",
    jobFunction: "Product Manager",
    experience: 6.1,
    salary: 2575000,
    domainName: "uber.com",
    stage: "Public Global",
  },
  {
    companyName: "Unacademy",
    jobFunction: "Marketing",
    experience: 3.4,
    salary: 1265000,
    domainName: "unacademy.com",
    stage: "Unicorn",
  },
  {
    companyName: "Qualcomm",
    jobFunction: "Software Engineering",
    experience: 9.3,
    salary: 3625000,
    domainName: "qualcomm.com",
    stage: "Public Global",
  },
  {
    companyName: "PolicyBazaar",
    jobFunction: "Sales",
    experience: 5.7,
    salary: 1965000,
    domainName: "policybazaar.com",
    stage: "Unicorn",
  },
  {
    companyName: "IBM",
    jobFunction: "Consulting",
    experience: 8.6,
    salary: 3125000,
    domainName: "ibm.com",
    stage: "Public Global",
  },
  {
    companyName: "Cred",
    jobFunction: "Software Engineering",
    experience: 3.3,
    salary: 1165000,
    domainName: "cred.club",
    stage: "Unicorn",
  },
  {
    companyName: "Deloitte",
    jobFunction: "Consulting",
    experience: 7.8,
    salary: 2825000,
    domainName: "deloitte.com",
    stage: "Public Global",
  },
  {
    companyName: "Dunzo",
    jobFunction: "Operations",
    experience: 2.6,
    salary: 965000,
    domainName: "dunzo.com",
    stage: "Series D+",
  },
  {
    companyName: "Capgemini",
    jobFunction: "Software Engineering",
    experience: 5.5,
    salary: 1665000,
    domainName: "capgemini.com",
    stage: "Public Global",
  },
  {
    companyName: "Udaan",
    jobFunction: "Marketing",
    experience: 4.9,
    salary: 1565000,
    domainName: "udaan.com",
    stage: "Unicorn",
  },
  {
    companyName: "Visa",
    jobFunction: "Product Manager",
    experience: 6.7,
    salary: 2675000,
    domainName: "visa.com",
    stage: "Public Global",
  },
  {
    companyName: "PhonePe",
    jobFunction: "Software Engineering",
    experience: 3.6,
    salary: 1265000,
    domainName: "phonepe.com",
    stage: "Unicorn",
  },
  {
    companyName: "EY",
    jobFunction: "Consulting",
    experience: 8.9,
    salary: 3325000,
    domainName: "ey.com",
    stage: "Public Global",
  },
  {
    companyName: "Meesho",
    jobFunction: "Operations",
    experience: 5.1,
    salary: 1765000,
    domainName: "meesho.com",
    stage: "Unicorn",
  },
  {
    companyName: "PayPal",
    jobFunction: "Software Engineering",
    experience: 7.3,
    salary: 2875000,
    domainName: "paypal.com",
    stage: "Public Global",
  },
  {
    companyName: "Byju's",
    jobFunction: "Marketing",
    experience: 4.5,
    salary: 1465000,
    domainName: "byjus.com",
    stage: "Unicorn",
  },
  {
    companyName: "KPMG",
    jobFunction: "Consulting",
    experience: 6.9,
    salary: 2475000,
    domainName: "kpmg.com",
    stage: "Public Global",
  },
  {
    companyName: "Dream11",
    jobFunction: "Product Manager",
    experience: 5.6,
    salary: 2065000,
    domainName: "dream11.com",
    stage: "Unicorn",
  },
  {
    companyName: "MasterCard",
    jobFunction: "Software Engineering",
    experience: 8.2,
    salary: 3125000,
    domainName: "mastercard.com",
    stage: "Public Global",
  },
  {
    companyName: "Razorpay",
    jobFunction: "Operations",
    experience: 3.8,
    salary: 1165000,
    domainName: "razorpay.com",
    stage: "Unicorn",
  },
  {
    companyName: "PwC",
    jobFunction: "Consulting",
    experience: 7.6,
    salary: 2975000,
    domainName: "pwc.com",
    stage: "Public Global",
  },
  {
    companyName: "Sharechat",
    jobFunction: "Software Engineering",
    experience: 4.3,
    salary: 1565000,
    domainName: "sharechat.com",
    stage: "Unicorn",
  },
  {
    companyName: "Tesla",
    jobFunction: "Product Designer",
    experience: 6.5,
    salary: 2775000,
    domainName: "tesla.com",
    stage: "Public Global",
  },
  {
    companyName: "Practo",
    jobFunction: "Marketing",
    experience: 5.9,
    salary: 1865000,
    domainName: "practo.com",
    stage: "Unicorn",
  },
  {
    companyName: "BCG",
    jobFunction: "Consulting",
    experience: 9.7,
    salary: 3625000,
    domainName: "bcg.com",
    stage: "Private Global",
  },
  {
    companyName: "Groww",
    jobFunction: "Software Engineering",
    experience: 3.1,
    salary: 1365000,
    domainName: "groww.in",
    stage: "Unicorn",
  },
  {
    companyName: "McKinsey",
    jobFunction: "Consulting",
    experience: 8.4,
    salary: 3325000,
    domainName: "mckinsey.com",
    stage: "Private Global",
  },
  {
    companyName: "upGrad",
    jobFunction: "Marketing",
    experience: 4.7,
    salary: 1665000,
    domainName: "upgrad.com",
    stage: "Series D+",
  },
  {
    companyName: "Bain & Company",
    jobFunction: "Consulting",
    experience: 7.9,
    salary: 3125000,
    domainName: "bain.com",
    stage: "Private Global",
  },
  {
    companyName: "Delhivery",
    jobFunction: "Operations",
    experience: 5.4,
    salary: 1965000,
    domainName: "delhivery.com",
    stage: "Public India",
  },
  {
    companyName: "Vedantu",
    jobFunction: "Software Engineering",
    experience: 4.8,
    salary: 1465000,
    domainName: "vedantu.com",
    stage: "Unicorn",
  },
  {
    companyName: "Acko",
    jobFunction: "Product Manager",
    experience: 6.2,
    salary: 2275000,
    domainName: "acko.com",
    stage: "Unicorn",
  },
  {
    companyName: "Ather Energy",
    jobFunction: "Software Engineering",
    experience: 3.4,
    salary: 1165000,
    domainName: "atherenergy.com",
    stage: "Series C",
  },
  {
    companyName: "BharatPe",
    jobFunction: "Operations",
    experience: 4.6,
    salary: 1565000,
    domainName: "bharatpe.com",
    stage: "Unicorn",
  },
  {
    companyName: "Digit Insurance",
    jobFunction: "Marketing",
    experience: 5.3,
    salary: 1865000,
    domainName: "godigit.com",
    stage: "Unicorn",
  },
  {
    companyName: "Eruditus",
    jobFunction: "Sales",
    experience: 4.2,
    salary: 1365000,
    domainName: "eruditus.com",
    stage: "Unicorn",
  },
  {
    companyName: "Fampay",
    jobFunction: "Software Engineering",
    experience: 2.3,
    salary: 965000,
    domainName: "fampay.in",
    stage: "Series A",
  },
  {
    companyName: "Gemini",
    jobFunction: "Product Designer",
    experience: 5.7,
    salary: 2065000,
    domainName: "gemini.com",
    stage: "Public Global",
  },
  {
    companyName: "Hasura",
    jobFunction: "Software Engineering",
    experience: 4.5,
    salary: 1665000,
    domainName: "hasura.io",
    stage: "Series C",
  },
  {
    companyName: "InMobi",
    jobFunction: "Marketing",
    experience: 6.4,
    salary: 2475000,
    domainName: "inmobi.com",
    stage: "Unicorn",
  },
  {
    companyName: "Jio",
    jobFunction: "Operations",
    experience: 7.1,
    salary: 2875000,
    domainName: "jio.com",
    stage: "Public India",
  },
  {
    companyName: "Khatabook",
    jobFunction: "Software Engineering",
    experience: 3.6,
    salary: 1265000,
    domainName: "khatabook.com",
    stage: "Series C",
  },
  {
    companyName: "Licious",
    jobFunction: "Sales",
    experience: 4.4,
    salary: 1465000,
    domainName: "licious.com",
    stage: "Unicorn",
  },
  {
    companyName: "MPL",
    jobFunction: "Product Manager",
    experience: 5.2,
    salary: 2165000,
    domainName: "mpl.live",
    stage: "Unicorn",
  },
  {
    companyName: "Ola Electric",
    jobFunction: "Software Engineering",
    experience: 3.1,
    salary: 1365000,
    domainName: "olaelectric.com",
    stage: "Unicorn",
  },
  {
    companyName: "Pine Labs",
    jobFunction: "Operations",
    experience: 6.8,
    salary: 2275000,
    domainName: "pinelabs.com",
    stage: "Unicorn",
  },
  {
    companyName: "Quikr",
    jobFunction: "Marketing",
    experience: 5.6,
    salary: 1665000,
    domainName: "quikr.com",
    stage: "Unicorn",
  },
  {
    companyName: "Rebel Foods",
    jobFunction: "Operations",
    experience: 4.3,
    salary: 1565000,
    domainName: "rebelfoods.com",
    stage: "Unicorn",
  },
  {
    companyName: "Swiggy Instamart",
    jobFunction: "Software Engineering",
    experience: 3.5,
    salary: 1165000,
    domainName: "swiggy.com/instamart",
    stage: "Unicorn",
  },
  {
    companyName: "Tata 1mg",
    jobFunction: "Product Designer",
    experience: 5.8,
    salary: 1965000,
    domainName: "1mg.com",
    stage: "Unicorn",
  },
  {
    companyName: "Udaan",
    jobFunction: "Sales",
    experience: 6.3,
    salary: 2475000,
    domainName: "udaan.com",
    stage: "Unicorn",
  },
  {
    companyName: "Zepto",
    jobFunction: "Software Engineering",
    experience: 2.7,
    salary: 1065000,
    domainName: "zepto.com",
    stage: "Series C",
  },
  {
    companyName: "Zeta",
    jobFunction: "Marketing",
    experience: 4.1,
    salary: 1765000,
    domainName: "zeta.tech",
    stage: "Series C",
  },
  {
    companyName: "boAt",
    jobFunction: "Product Manager",
    experience: 5.5,
    salary: 2065000,
    domainName: "boat-lifestyle.com",
    stage: "Unicorn",
  },
  {
    companyName: "Cars24",
    jobFunction: "Operations",
    experience: 3.2,
    salary: 1265000,
    domainName: "cars24.com",
    stage: "Unicorn",
  },
  {
    companyName: "CoinDCX",
    jobFunction: "Software Engineering",
    experience: 4.7,
    salary: 1865000,
    domainName: "coindcx.com",
    stage: "Unicorn",
  },
  {
    companyName: "CoinSwitch Kuber",
    jobFunction: "Marketing",
    experience: 3.9,
    salary: 1465000,
    domainName: "coinswitch.co",
    stage: "Unicorn",
  },
  {
    companyName: "Cult.fit",
    jobFunction: "Sales",
    experience: 5.4,
    salary: 2165000,
    domainName: "cult.fit",
    stage: "Unicorn",
  },
  {
    companyName: "Dealshare",
    jobFunction: "Operations",
    experience: 4.8,
    salary: 1665000,
    domainName: "dealshare.in",
    stage: "Unicorn",
  },
].map((el, i) => ({
  ...el,
  id: i,
}));

export default data;
